<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20161207232351 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('DROP TABLE obisconcept_NeosBlog_domain_model_category_posts_join');
        $this->addSql('DROP TABLE obisconcept_NeosBlog_domain_model_tag_posts_join');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE obisconcept_NeosBlog_domain_model_category_posts_join (NeosBlog_category VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, typo3_model_nodedata VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_55BB2E4E363B10B0 (NeosBlog_category), INDEX IDX_55BB2E4EDE65D1EC (typo3_model_nodedata), PRIMARY KEY(NeosBlog_category, typo3_model_nodedata)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE obisconcept_NeosBlog_domain_model_tag_posts_join (NeosBlog_tag VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, typo3_model_nodedata VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_5A11FDBB4E662292 (NeosBlog_tag), INDEX IDX_5A11FDBBDE65D1EC (typo3_model_nodedata), PRIMARY KEY(NeosBlog_tag, typo3_model_nodedata)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE obisconcept_NeosBlog_domain_model_category_posts_join ADD CONSTRAINT FK_55BB2E4E363B10B0 FOREIGN KEY (NeosBlog_category) REFERENCES obisconcept_NeosBlog_domain_model_category (persistence_object_identifier)');
        $this->addSql('ALTER TABLE obisconcept_NeosBlog_domain_model_category_posts_join ADD CONSTRAINT FK_55BB2E4EDE65D1EC FOREIGN KEY (typo3_model_nodedata) REFERENCES typo3_typo3cr_domain_model_nodedata (persistence_object_identifier)');
        $this->addSql('ALTER TABLE obisconcept_NeosBlog_domain_model_tag_posts_join ADD CONSTRAINT FK_5A11FDBB4E662292 FOREIGN KEY (NeosBlog_tag) REFERENCES obisconcept_NeosBlog_domain_model_tag (persistence_object_identifier)');
        $this->addSql('ALTER TABLE obisconcept_NeosBlog_domain_model_tag_posts_join ADD CONSTRAINT FK_5A11FDBBDE65D1EC FOREIGN KEY (typo3_model_nodedata) REFERENCES typo3_typo3cr_domain_model_nodedata (persistence_object_identifier)');
    }
}